### ISSUE TITLE
Scout Report photos not attaching

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#123]
After Arches 5, there is an issue with photos not attaching to reports. It looks like when you click “add”, nothing happens. Normally once you click “add” the group of photos shows up as a dropdown under Step 6 but that is not happening. Also, once you click “add”, normally that button disappears and you then have the option to edit or delete but that isn’t happening up either – the text below the image still says unsaved. After you click "Add" the wheel comes up like it's thinking, but nothing occurs. It will allow you to "Cancel Edit" but not "add".

![image](https://user-images.githubusercontent.com/54329725/77955016-89780e80-729d-11ea-9587-0160a936225e.png)

**Comment by mradamcox** [comment]
The problem here was that new config info is now expected on FileListDatatype nodes. To fix it I just had to temporarily set `OVERRIDE_RESOURCE_MODEL_LOCK = True` and then in the Arches Designer go to the photo node and then save it. The new settings were then properly saved. This error wasn't occurring in the staging or local environments because those configs are automatically set with the resource graphs are loaded anew.
