### ISSUE TITLE
Typo on the Photo Submission Form

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#134]
One of our Scouts noticed a typo in the "Upload Documents" section on the "Step 6: Photo Submission" page of the Scout Report. The r is missing from the word drop in "Drag & Drop". 

While you are editing this, could you also add a statement that lets them know that they can only upload 10 items at a time? So maybe "You may upload as many documents as you wish, but you can only add 10 items at a time. The maximum size of any single file is 20MB."

![image](https://user-images.githubusercontent.com/54329725/78166266-7dfe2200-741a-11ea-833d-081b86157a98.png)

**Comment by mradamcox** [comment]
@coherit whenever you address this, could you look at the Arches core code and see if this is still a bug there? If so we should contribute the fix there (from Legion's Arches fork) and if not we should see if there's been a minor/micro release that we can upgrade to.

**Comment by coherit** [comment]
This was fixed in Arches master on March 18
https://github.com/archesproject/arches/commit/ff8900dc4fc146f30b063abec2b918f634a029a6#diff-087bfc96fd5f766c825ba62f19fe1e0b

It's been pulled to master but no official release since 5.0.0. 

Since @kkemp85 requested the change to the file # upload sentence, I've copied the template down to fpan and fixed both there manually. Committed in branch https://github.com/legiongis/fpan/tree/134_filewidget_typo

**Comment by mradamcox** [comment]
@kkemp85 can you check this out and close if everything looks good?

**Comment by kkemp85** [comment]
@mradamcox yes looks good!
