### ISSUE TITLE
Layout issue in search bar when searching by word or phrase

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#136]
A scout pointed out to us that when she searched for a cemetery name, blue blocks would overlap her search at the top and it looks a bit glitchy. After testing this out myself I realized it has to do with a new search feature when you search by word or phrase. You have the option to search the word by its "Term Matches", I think a direct match in a resource name for that word, or by "Concepts" which searches any part of a resource's content for that word. 

This is a neat feature that I like, but as you can see from the images, it's not showing up properly in the search bar. The new "Term Matches" and "Concepts" blocks are overlapping over the results. It would be great to clean this up so it's more useful!

![image](https://user-images.githubusercontent.com/54329725/78263104-849aa100-74cf-11ea-9709-e6709893486c.png)

![image](https://user-images.githubusercontent.com/54329725/78263016-692f9600-74cf-11ea-8118-f95f074acbee.png)

**Comment by mradamcox** [comment]
@kkemp85 Yeah, I noticed this too. I haven't used a default Arches 5 app enough yet to know about whether this a general issue or one specific to our installation.

**Comment by coherit** [comment]
This is likely in core Arches and is the result of bad math on the box model in arches.css. The left pane is set to 400px wide, the two tabs are set to 195px each (10px of white space), but the margins of the search widget pulldown is set to 7px (left + right = 14px). So, the tabs end up stacking instead of sitting flush side by side.

Fixed by setting width of tabs to 175px each. Committed in branch https://github.com/legiongis/fpan/tree/136_search_tabspacing
