### ISSUE TITLE
Scout Report looks different after Arches 5 upgrade

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#138]
A scout pointed out to us that the Scout Report looks different now after the Arches 5 upgrade. It's obvious things would change, but I thought I would ask about it for my scout anyway. The first two pages (Steps 1 and 2) now have different symbols next to them instead of the pages symbol like the others in the tree structure. They also highlight differently and have extra instructions in green on the page itself. This isn't really an issue but more of a question. Is this because the first two pages are the main reference pages for the resource? Is there a way to make the description go away?

I think the reference to the "card" in the description and the green and yellow highlighting threw off my scout. It's no biggie if it can't be changed, just wondered about it.

![image](https://user-images.githubusercontent.com/54329725/79141068-0ec3ee80-7d87-11ea-8dd5-c0c23a4c046e.png)

![image](https://user-images.githubusercontent.com/54329725/79141094-1aafb080-7d87-11ea-86d7-ede40279557a.png)

![image](https://user-images.githubusercontent.com/54329725/79141129-2ac79000-7d87-11ea-80f2-8561a8cfa925.png)

**Comment by mradamcox** [comment]
Yeah, these are just some design changes that they implemented. The green highlighting, green note, and the `</>` symbol all serve as reminders to the editors that those nodes will be used in the displays of the resource throughout the app. In the display name, or the display description (in the list of search results) or in the map popup. I don't really think it's worth trying to get rid of as it can be useful in some situations, but do appreciate that the scouts are paying such close attention!

The yellow highlighting is a little different, it pops up when you have edited but not saved a card. It's a little wonky here though, because we have added some custom logic to that second page. As you can see in the screenshot, the user name is automatically placed in the Your Scout ID field. The interface recognizes this as an edit, even though the scouts don't have to do it manually. So it's a little strange, but I think it still makes sense and doesn't break anything.
