### ISSUE TITLE
Indexing Issue with Archaeological Sites

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#154]
After we re-indexed resource displays to be SITE ID - SITE NAME, quite a few archaeological sites still have the old-style indexing SITE NAME (SITE ID). I noticed this was the case on many sites mostly in the mid to southern Florida counties. I have a few specific examples of these issues at sites like SJ00045, SJ03702, LL00045. HI12150, SO00029, and GL00015, but there were too many sites to count. I saw this issue in sites with site IDs that started with SJ, LL, HI, GL, HR, PA, PI, and PO. There are probably many more but I was unable to go through the whole database to confirm.

**Comment by mradamcox** [comment]
@kkemp85 Ok, thanks for this, I will reindex the Archaeological Sites directly on the server tonight and I think that will solve this issue no problem. I think I know what happened: The server-side command line operation for reindexing (when you do the entire database as I usually do, rather than just one resource type) deletes the entire resources index before beginning. This means that when the resource count is back up to the correct total in the search page, the operation is complete. When you just reindex resources of one type, I realize now that all of the existing entries are not deleted ahead of time, they are just reindexed in place. So, ultimately, I just stopped the process too early last time around, thinking it was finished (based on the search page count) when it wasn't actually done.

**Comment by kkemp85** [comment]
@mradamcox They all look correct now, thank you.
