### ISSUE TITLE
Scout Report instructions overwritten with move to Arches 5.1

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#182]
With the new update to Arches 5.1, some new underlying settings overwrote the instructions we wrote up to go on the landing page of the Scout Report. We would like the stock page to be reverted back to the instructions.

![image](https://user-images.githubusercontent.com/54329725/106929758-c1808700-66e2-11eb-985d-60cfd8915b2e.png)

**Comment by mradamcox** [comment]
This happened because core arches had been using a template called `new-editor.htm` and we had overwritten that one, but now that core arches has reverted to using `editor.htm` we need to override that template instead. Best way to do this is migrate the core arches `editor.htm` template to our app and then paste in our custom code to re-apply the HMS instructions.

**Comment by coherit** [comment]
This has now been fixed in https://github.com/legiongis/fpan/tree/182_scoutreport. I'll file a pull request for your review.
