### ISSUE TITLE
Broadening the Historical Structure filter in the FMSF to HMS Plugin

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#235]
I'm wondering if while looking into #234, we could look at the possibility of expanding the automatic filter that structures go through in the plugin (as seen below) to include state forests and wildlife management areas. Now that we have more managers using these accounts, it would be good to add them to the regular filter. They are large areas and the process for me to go through and compare which are already in Arches can take a lot of time.

<img width="384" alt="image" src="https://user-images.githubusercontent.com/54329725/151564189-f25ec4e6-ed0f-4649-91f4-b114fcb50588.png">

**Comment by mradamcox** [comment]
@kkemp85 I'm setting up the new FMSF import process to use Management Areas that we have in our database, instead of the separate shapefile that we were using the QGIS plugin. However, for now I'll still be hard-coding the categories into the process (we could make it configurable during each data import session in the future.

Could you specify here which categories I should include? You can use the Django admin backend to explore. Also, I have added the NR districts in as Management Areas (locally, not in production) so they can be used in this filter as before.

**Comment by kkemp85** [comment]
@mradamcox If I am understanding you correctly you are asking me to list which management area categories to apply the historic structure filter? If that's the case I would say it needs to be applied to all categories except the FPAN region category. 

I see that you are taking care of the NR district filter, but just want to make sure that we also filter in the lighthouses as well.

**Comment by mradamcox** [comment]
Ok, sounds good, we'll just use all management areas beside the FPAN Regions in that case. The spatial filter during upload will take longer to run, but that's fine, it will be configured to run in the background anyway. I do still have the lighthouse filter in place, as well as filtering out any structures that are marked as destroyed.
