### ISSUE TITLE
Updating a Scout's Profile

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#236]
With the new Scout profile system, if you click the link to update the Scout profile, it opens a window where you can update the more in-depth Scout information including region and interests. 
<img width="572" alt="image" src="https://user-images.githubusercontent.com/54329725/152864343-aee540cb-8f75-4283-8080-a10c979c9275.png">

But I noticed that once you are there, there isn't a way to get back to your main profile. After you click "Update my profile" at the bottom, it just stays on the same page. If you click on the "View Profile" link at the top, you also just stay on the same page. The only way I figured out how to get back is to click "Home", then click on "Explore the Database", then from there click on "My Profile" and it will take you to the main page. I think we need a better way for people to get back to their main profile after updating.

Also, would be good if we could add a statement that says clicking on the "update my profile" link will allow for Scouts to update their region, interests, and address. From what shows on the profile now, it looks like the only information they can access is name, email, and phone number.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/54329725/152863898-5cfbdbbc-b057-41fb-adfd-f0afc0d8bc91.png">

**Comment by mradamcox** [comment]
Good catch. We initially wanted to combine all of the profile content into one page of course, but that became too complex to integrate with the default Arches profile content. But, clearly, the full usability of linking out to a separate page wasn't really followed through. @kkemp85 do you think these changes would be sufficient:

1. Add redirect to /user page after clicking "update my profile"
2. Add "back to basic profile" (or better verbiage?) link for people who don't want to make an update
3. Add more explicit subtitle that makes clear a user can change their region etc.
4. Remove the change password link here because it already exists in the basic profile page.
5. On the basic profile, remove external link icon which implies that scout profile will open in a new tab (it doesn't, and I think it's better that it doesn't)

**Comment by kkemp85** [comment]
@mradamcox Yes, I think all of that will work great!
