### ISSUE TITLE
Errors on profile page and main map

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#273]
I am getting an error 500 message on the profile page of all accounts I log in to, even the admin page, and am also getting a "request failed" error when trying to load the map page for land manager accounts. I texted @mradamcox about this issue today since it was working fine this morning.

![image](https://github.com/legiongis/hmsf-md/assets/54329725/04f69cd7-f095-4b96-b3ba-bfc7f4fb5ce7)

**Comment by mradamcox** [comment]
This was due to an unhandled error in a couple of advanced filtering functions which attempt to find the FMSF id in a Scout Report. Two completely blank Scout Reports had been created recently, causing a `TypeError` due to `NoneType` values when the function tried to find the ID. A hotfix has been applied to address the error, but I'll leave this ticket open until I can push the fix to the main branch.

The blank reports are

- https://hms.fpan.us/report/4e4f7c46-1b64-47cb-b75a-95cb89955aaf
- https://hms.fpan.us/report/2a072f93-6ca1-425c-8239-3aa3ae528430

We can delete these now that the ids are saved here for future reference.
