### ISSUE TITLE
Scout Accounts can add resources other than Scout Reports

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#275]
When I logged into my Scout account I noticed that when I clicked on the building to add a new Scout Report the option was there to add arch sites, structures, and cemeteries too. I did notice that a scout had accidentally tried to add a cemetery the other day but thought it was a fluke. I tried to look to see if this was an issue I could resolve but couldn't figure it out. We definitely need this fixed before chaos ensues!

![image](https://github.com/legiongis/hmsf-md/assets/54329725/55fefa9a-bccc-43e7-bd3f-a52cca0c1d02)

**Comment by mradamcox** [comment]
Checking over the permissions, ultimately the best way to handle this is to remove the Resource Editor group from all users, and just assign the Crowdsource Editor group across the board. Then we can use the Arches UI in the Graph Editor to do the following: Assign **Create/Update** permissions to the Crowdsource Editor group for all resource models, and 2) Assign **Create/Update** permissions to the Crowdsource Editor group for just the Scout Report resource model. I've done this now in the production site. Additionally, I

-  Assigned Crowdsource Editor to all Scouts and Land Managers in the Django backend, and removed Resource Editor from all users
- Changed user profile creation so that Resource Editor is no longer assigned automatically
- Added information about this to /docs/permissions.md

Encountered a bug in Arches while working on this, logged it here: https://github.com/archesproject/arches/issues/10702.
