### ISSUE TITLE
State Park Sites

### ISSUE THREAD

**Issue by rosulliv14** [legiongis/hmsf-md#50]
Was just going through looking at the state park sites you uploaded. Looking great and fantastic to see this coming together. I did notice a few sites missing that I know of within state parks, so will need to do some checks to make sure sites didn't get left out. In particular, 8SJ03536 within Anastasia State Park and 8FL00007C within Bulow Plantation Ruins State Park. Obviously didn't get a chance to check every state park but this is something we need to be on the look out for as well.

**Comment by mradamcox** [comment]
@rosulliv14, when you get a chance, could you do a little spot-checking on these sites? Now that all of the archaeological sites have been loaded, these will hopefully be present. However, there were some sites that had errors in the geometry I received from FMSF, so I was unable to load them.

**Comment by mradamcox** [comment]
@rosulliv14 After the latest update and restructuring, would you be able to take a look at this again? I wonder if the issue remains. Those two that you mentioned indeed are not present in the current database. Is there any chance that they are structures? I believe the only structures we have are lighthouses and those within a few specific historic districts.

**Comment by kkemp85** [comment]
@mradamcox I just looked into this, and both of those are archaeological sites not structures. Is this something that may be solved once we do the next site upgrade from the FMSF?

**Comment by mradamcox** [comment]
@kkemp85, yes, if those are archaeological sites that have been added to FMSF since we _first_ installed the database, they will not be in the Arches db until we do a migration update from FMSF (which will be within a few months, I hope). If that is the case, could you close this ticket in favor of #53?

**Comment by kkemp85** [comment]
@mradamcox so those sites were added to the FMSF _before_ you first installed the database, so they should already be in Arches. I think what you said in a previous comment is what occurred, there was some issue in the geometry of these sites and that's why they didn't load when you first created the database. Which means that this issue will probably occur again when you do get the FMSF upgrade done for Arches. So not sure how you want to proceed. It is technically a separate issue from the upgrade. And I bet this probably occurred with more sites than just these two, so we will need to figure out how to track that as well to fix all of them.

**Comment by kkemp85** [comment]
@mradamcox since you are doing the update now you probably already have a list of sites that didn't make it into Arches the first time around (I remember you saying there was a 300 site discrepancy), but just noticed that HI00117C (Egmont Key) is also missing so figured I would document that here.

**Comment by kkemp85** [comment]
@mradamcox disregard that last comment, HI00117C is in Arches, my mistake!

**Comment by kkemp85** [comment]
@mradamcox These sites are properly in the database now. Hopefully the process you set up will eliminate these kinds of issues in the future.
