### ISSUE TITLE
GIS update schedule for Site File data

### ISSUE THREAD

**Issue by rosulliv14** [legiongis/hmsf-md#53]
For this Wish List... Need to think of a schedule for updating data from FMSF and include that in work plan for Adam

**Comment by mradamcox** [comment]
@rosulliv14 and @emjaymur I'm waiting to hear back from Chip about this, but you may know too: about how many sites do you think are added per month, or per quarter? Same question for structures and cemeteries.

**Comment by mradamcox** [comment]
For the record, here's the info I got from Chip a while ago: 

> We add around four to five thousand resources to the inventory annually, although the overwhelming majority of those are buildings.  I would say yearly updates are probably sufficient for your purposes as newly added sites will have just been visited during the site recording process.

**Comment by mradamcox** [comment]
@kkemp85 @rosulliv14 Finally finished this. Instead of making a schedule per se, I've made [this plugin for QGIS](https://www.notion.so/legiongis/FMSF-to-HMS-QGIS-Plugin-1a413cd8aa334e9bb2180be8c6841665), so that you all can request the FMSF data as shapefiles and process it yourself whenever you want. You'll still need to pass me the CSV files at the end for the final upload, but the majority of the work will be done by the tools in the plugin that filter out the new FMSF sites from those already in HMS. Full details in the link above.
