### ISSUE TITLE
Archaeological site outlines to show on scout maps

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#56]
We've talked about this before, but just adding it in as a wish list item in case any future restructuring will help make this easier to do. It's creating a little confusion about site assignments as scouts can't quite see everything that has be assigned to them.

The outlines of archaeological sites do not show up on the main landing map of scout accounts. You can find them when searched/sorted for, and only marked with gray markers.

**Comment by mradamcox** [comment]
@emjaymur yeah, this is a really good issue to bring up. It's because as a whole, the Scouts don't have access to the archaeological sites locations, and the resource overlays on the map are not filtered in the same way that the search results are when scouts look for their assigned sites. Another way to think of this ticket is to filter all resource map layers to match the current search results. Big +1 from me on that.

**Comment by mradamcox** [comment]
@emjaymur I believe this is now fixed. Can you confirm and close this ticket if so?

**Comment by mradamcox** [comment]
@kkemp85 Do you think you could have a look at this ticket and decide whether it's been addressed since it was created?

**Comment by kkemp85** [comment]
@mradamcox I just tested this out with a dummy scout account I have and the arch site polygons show up fine so it seems resolved to me.
