### ISSUE TITLE
Un-assignable sites

### ISSUE THREAD

**Issue by emjaymur** [legiongis/hmsf-md#62]
Just starting a list with sites that I could not assign to scouts in the system. The dropdown menu was blank.

BR00200

**Comment by mradamcox** [comment]
@emjaymur, in the case of the site you listed so far, it's a shipwreck and my guess is that it fell outside of the FPAN region boundaries I used early on in the process of automatic region assignment. (I've reworked that process a couple of times.) You can make this site available by assigning the correct region in the "Located in..." tab in the Site Location menu.
![image](https://user-images.githubusercontent.com/10427268/48019919-33c82280-e0fa-11e8-8b69-b94d3e8ed78c.png)

I called these attributes "read-only" just to discourage editing them, because certain permissions operations depend on them, in reality an admin can update them.
