### ISSUE TITLE
Some sites displayed twice in database

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#77]
I've noticed that a few sites are showing up twice in Arches. So the same site will have different Scout Reports on each resource. I've seen at least 3 sites that are this way. For example, Conch House Groin (SJ04874) has one site listing with 2 scout reports recorded and another with none. See the attached photos. I thought that I could fix this myself and just delete one of the duplicates but I was afraid that I might somehow delete the site entirely from Arches. Adam, do you think I can just delete one of the duplicates and that would solve the issue or is this something you have to handle from your end?
<img width="254" alt="SJ4874" src="https://user-images.githubusercontent.com/54329725/70094281-342e3800-15f0-11ea-9c83-bf9d981520f4.png">
<img width="944" alt="SJ4874b" src="https://user-images.githubusercontent.com/54329725/70094289-37292880-15f0-11ea-9f5c-b6c24c0542a5.png">
<img width="942" alt="SJ4874c" src="https://user-images.githubusercontent.com/54329725/70094291-398b8280-15f0-11ea-8b69-569f635dec1b.png">

**Comment by mradamcox** [comment]
@kkemp85 You can safely delete whichever entry you want. The key is in the UUID (the long string of letters and numbers) that is in the url when you are viewing the report. That is the internal identifier for the site itself, so because it's different in each one, they are completely independent.

One note: if you delete a site that has scout reports attached to it, they will not be automatically deleted. So, it would be best to delete those reports individually and the delete the site itself.

**Comment by mradamcox** [comment]
Ok, I just did some checking on an export of all the sites, and there are just three duplicates:

    PI00031
    DI00029
    SJ04874

Very strange. Perhaps these are duplicated in FMSF, or it's possible there was a problem doing the initial import (though it would be strange for there to be only three errors if that was the case). You can safely find these duplicates and remove them.

**Comment by kkemp85** [comment]
I just fixed this! It's strange to me that all three of the duplicates you found, were the ones I found in the system on my own which prompted me to open this issue! Thank you!
