### ISSUE TITLE
User ID should be autopopulated in the "Your Scout ID" field

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#79]
When a scout accesses this page in the Scout Report, their id should be automatically placed into the top line. In the example below, `cjmorton` should be added. ~~This field should also be disabled (visible but not editable).~~ This field should remain editable for now.
![image](https://user-images.githubusercontent.com/10427268/70877044-7b69e080-1f81-11ea-85b9-661bd9f5731c.png)

**Comment by coherit** [comment]
@mradamcox  Okay, I made progress, but it won't be ready for tonight's push to production, so no commits yet. Should I start a new branch? Let me know what makes things easiest for you.

GOOD: I am successfully able to set the value of the text widget to {{user.username}} using a ko if/ifnot statement to only target the node_id for the Scout ID node -- because we don't want to create a new widget, I am working in templates/views/components/cards/default.htm

BAD: It fails validation and throws a ValueError at /tile when I click "Add" for that card group (all the other cards can be added fine and the instance is committed, just without the 2nd card). So I'm still missing something or strongarming it in the wrong way. I need to spend more time with this to understand it better. 

![Capture1](https://user-images.githubusercontent.com/3217017/72189138-165faa00-33ca-11ea-97a1-92d4877a360d.JPG)


![Capture](https://user-images.githubusercontent.com/3217017/72188800-380c6180-33c9-11ea-8f8f-6f2e07d198e0.JPG)

**Comment by mradamcox** [comment]
Ok, no problem at all, and great progress. Sounds like it's something to do with how the value is placed in the field or something.

If you could make a new branch just for this ticket that would be great. I'll be merging the coherit_frontend branch into master momentarily, so you could make it from either one and I don't think there will be a problem.

**Comment by coherit** [comment]
I've worked on this quite a bit and keep hitting a wall. I've tried switching focus to the text widget (rather than the card component) and using value instead of textInput data-binds, intercepting the defaultValue param....but no matter what, I can't successfully prepopulate the textfield and validly pass the tile save function. Going to give the arches forum a shot.

**Comment by mradamcox** [comment]
Ok great, I think the forum is a good way to go, we'll just see if something turns up.

**Comment by coherit** [comment]
made some good progress on this -- branch [coherit_username](https://github.com/legiongis/fpan/tree/coherit_username) now has this feature. Currently, it is working on a hardcoded value of "abc". I'll work on passing the {{user.username}} variable from the template to the viewmodel next. Should be an easier task now that the new binding is working on the Scout ID node. 

Andrew Jones on the forum got me on the right track. I thought I didn't have to use the subscribe function since I was using the textInput binding, but I did in this case. I'm using both the regular subscribe and the beforeChange subscription to get the initial value that will be passed by the django template and still allow the user to edit the field.

**Comment by mradamcox** [comment]
@coherit great, thanks for sticking with it and I'm glad the forum was helpful. I don't think I'll be able to test/deploy this until Friday, so feel free to keep working on it.

**Comment by coherit** [comment]
@mradamcox - this may be as far as I'm able to get until Monday due to my schedule:

latest [commit](https://github.com/legiongis/fpan/commit/223b6437bd405bf8ed2ecf5979d3ef613d841cd1) has made progress, but still buggy:

Testing use cases (using cjmorton as example):

When creating a new scout report, the username cjmorton is populated by default...

1.  if you don't touch the scout user id field and complete the rest of the card, cjmorton is entered into the db and is displayed as the values on the left sidebar and card [PASSES]

2. if you edit the scout user id field to cjmortone and complete the rest of the card, cjmortone is entered into the db but cjmorton is still displayed as the values on the left sidebar and card [BUG]

3. if after adding the card the first time, you then edit the scout id field again, the sidebar and card will display the new value BEFORE and AFTER pressing Add [PASSES]

4. if you jump to the report, the correct value (whatever was last committed to the db) is shown [PASSES]

5. if you then choose to edit the report, the default username will once again appear to overwrite the form field and sidebar label, even if another value is in the db [BUG]

My ko.extender function in media/js/views/components/widgets/text.js needs to deal with use cases 2 and 5 above when a value is already present from the database, do not replace with defaultVal. There is could be a property in params that may be used and added to the if statement on the extender. The sidebar on the left is showing displayValue, so that should fix itself if the form field is fixed.

**Comment by coherit** [comment]
@mradamcox ok, finally have solved this. now passes all use cases above. [Latest commit](https://github.com/legiongis/fpan/commit/8c29863bff342da2861b76ef37a373c55b1b4787) on coherit_username is ready for your and client testing.

**Comment by coherit** [comment]
@mradamcox edited the widget to not use cid and instead use the node.id -- [latest commit](https://github.com/legiongis/fpan/commit/f853487df0919ab9e42a3f5b5fe772632e141b27) is ready to merge.

**Comment by mradamcox** [comment]
@kkemp85 This is now deployed on the staging server, can you take a look and close this ticket if everything works for you? Thanks!

**Comment by kkemp85** [comment]
Looks good to me!
