### ISSUE TITLE
Fix Styling in Left-Hand Panel

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#81]
Some of the CSS class names, etc. must have changed in the upgrade to 4.4. This should be fixed for all user types (admin, scouts, state land managers). The image below is for scouts, and the background of the entire thing should be blue. The "TOOLS" text should be changed too. Either white or something darker (as appropriate with the rest of the site).

![image](https://user-images.githubusercontent.com/10427268/70877518-64c48900-1f83-11ea-848b-e8e0db959ddc.png)

**Comment by coherit** [comment]
I've addressed this issue in the coherit_frontend branch => [commit 71c49d](https://github.com/legiongis/fpan/commit/71c49d39a67af0fcc19892e03cf0c857f65ff016)

I made an initial commit to make the text across the entire site a bit more accessible -- changing the base body font size to 16px (from 11-13px -- it varied in places -- 16 is generally accepted as an accessible base) and then setting all headers and .small text to using ems so that if you want to change the base font size in the future, everything will change proportionately. Unfortunately, the Arches reports' font sizes are all hard-coded in the arches.css and thus have not been addressed here. 

The left sidebar is now consistently styled for each user type admin/anon (maroon/lt maroon), scout (turq/orange), and state (green/blue). Hover submenus now appear the same color as the main menu bar. The submenu items have a bit more padding to allow for hovers to appear consistently. 

I swapped out the Arches logo for the FPAN sun in top left.

**Comment by mradamcox** [comment]
@coherit Thanks, I like the font upgrades and the styling/icons look good. Could you also set the background in this weird little upper left square (for all categories of users-it should match the background color of the buttons below it)?
![image](https://user-images.githubusercontent.com/10427268/72097213-7af30a00-32e1-11ea-9768-c8a5f74bba08.png)

**Comment by mradamcox** [comment]
@kkemp85 could you have a look at these changes on the staging server and let us know what you think? Especially the font size increase.

**Comment by kkemp85** [comment]
@mradamcox Looks good to me! The icons and text are much easier to see now!

**Comment by coherit** [comment]
@mradamcox .brand-title no longer has the beige rice paper background and is set to the color for each user group. [Commit f61199f](https://github.com/legiongis/fpan/commit/f61199fa0d027dc0ff2367225a024136819a45bd)
