### ISSUE TITLE
Can't Connect to HMS Arches from Mobile App

### ISSUE THREAD

**Issue by mradamcox** [legiongis/hmsf-md#85]
In the mobile app, when trying to connect to the HMS database through the app, there is silent failure and no connection is made. Though discussions with the developers, this is a) a lack of good error reporting in the app and b) a problem with our server; I was able to successfully connect to another server.

After digging around I believe the issue is that we are using HTTPS and I'm not sure the app supports that. I have [posted in the Arches forum](https://groups.google.com/forum/#!topic/archesproject/0ZNVu5Y8iGk) with more information, and will wait to hear if others have input there.

**Comment by mradamcox** [comment]
@coherit could you explore this ticket by trying to connect to the staging server installation? You may need to begin by installing couchdb on that server, but you'll also likely need to create an oauth application. https://arches.readthedocs.io/en/stable/api/#authentication Also there's an Apache note here about the collector app: https://arches.readthedocs.io/en/stable/serving-arches-with-apache/

**Comment by coherit** [comment]
@mradamcox can you please put the Arches admin user's password for staging on Notion? (or here) I can't find the initial user info file with all the password combos on the server. I'd like to be able to see the project manager from the front end too. Thanks!

**Comment by mradamcox** [comment]
@coherit done.

**Comment by coherit** [comment]
Okay, I've spent some time on this -- installed couchdb 2.3.1, followed all instructions across arches and couchdb for xenial/wsgi. I have a project activated (nickname = FPAN) only for the admin user.

When I try to add the instance via the collector app, I can trigger the following error log entries:
```
Forbidden (Referer checking failed - no Referer.): /auth/user_profile
WARNING:django.security.csrf:Forbidden (Referer checking failed - no Referer.): /auth/user_profile
```
Commenting for now just to keep track of this as I look into it further.

**Comment by coherit** [comment]
...and I see I just replicated what @mradamcox got too when I search the arches forums...I've been looking at the same stackoverflow and github issue reports too regarding the error message.

There isn't anything apparently different about this server than the others that you set up which work over https (like oas_jamaica). I'm going to keep digging into this...

**Comment by mradamcox** [comment]
Ok, do make sure to read that forum post as this looks similar to what I've
seen in the past.

**Comment by coherit** [comment]
@mradamcox  spitballing here...do you think this could be related to the fpan overrides of views/auth.py? 

When I try to connect via the app, the class  CouchdbProxy from views/api.py does log "Dispatching Couch Proxy" which suggests that the app is engaging with the api. The referer error on auth/user_profile then suggests a csrf issue with auth.py.  Wondering if one of your classes needs a csrf_exempt added to it or something. 

Stepping away now but just leaving these comments so I don't forget. Plus the below link for later ref:
https://docs.djangoproject.com/en/1.11/ref/csrf/

**Comment by coherit** [comment]
I'll be working on this today (Monday) and will thus need to be using the staging server as the test bed. I'll still develop locally on a separate branch and push/pull -- checking out master again and restarting apache if my branch breaks things unexpectedly on staging. I'll keep all settings changes on staging in the settings_local file with quick ability to comment out my changes. Just a heads up in case you need staging today for other purposes -- just let me know.

**Comment by coherit** [comment]
I made some debugging progress on this today and I suspect it has to do with the additional views added to auth.py by the fpan app. In the new 85_apiconnect branch, I've added some heavy debug logging (just tail -f on the error-fpan...log). I've edited urls.py to use an fpan version of api.py. I've added a @csrf_exempt decorator to auth in fpan/views/auth.py. I'm now getting the following log msg:
```
[Mon Mar 23 15:27:29.263014 2020] [wsgi:error] [pid 2657:tid 140001365202688] Dispatching Couch Proxy
[Mon Mar 23 15:27:29.263458 2020] [wsgi:error] [pid 2657:tid 140001365202688] 66
[Mon Mar 23 15:27:29.263672 2020] [wsgi:error] [pid 2657:tid 140001365202688] 101
[Mon Mar 23 15:27:29.263880 2020] [wsgi:error] [pid 2657:tid 140001365202688] 147
[Mon Mar 23 15:27:29.319741 2020] [wsgi:error] [pid 2657:tid 140001365202688] Dispatching Couch Proxy
[Mon Mar 23 15:27:29.431545 2020] [wsgi:error] [pid 2657:tid 140001365202688] Not Found: /auth/user_profile
```

This is telling me that CouchdbProxy is firing (66), APIBase (101), and Surveys (147) in api.py. The last is where the call to user_profile happens. I'm no longer getting the csrf_exempt error. I get another Dispatching Couch Proxy from arches/views/api.py firing everything all over again, which I believe is what is leading to the 404 error in the end and the collector failing. 

I'm not sure how to get Arches to not load api.py again from arches/urls.py.  The first 4 log messages are being triggered by fpan/views/api.py while the last two are coming from arches/views/api.py. Leaving this for the day and will checkout master on staging.

**Comment by mradamcox** [comment]
@coherit Great work on this so far. It does make sense that custom auth views may be impacting this, they were put in place before the mobile survey aspect of Arches was developed. Your work on this comes right as I'm updating the app to work with Arches 5, part of which does involve some api-related changes. So it'll be really good if you're able to keep track of all the specific changes you make, because you may need to remake them in a new branch, after the v5 update. We'll see.

**Comment by coherit** [comment]
Good news: the Collector now connects to the server. Files edited: urls.py, auth.py, and settings_local.py
To test:  url = https://fpan.legiongis.com; nickname = test; login with the admin credentials

Bad news: we can add new resources but can't sync because of a datetime formatting error on the scout report model. See below.

There were a few compounding errors:

- CSRF errors -- WARNING:django.security.csrf:Forbidden ... this was solved by: 
  - editing fpan/views/auth.py and adding @csrf_exempt to the auth function
  - adding several exceptions in settings_local.py 
 _the above edits should be tested to see which ones are really required_ 

- 404 errors -- once CSRF was fixed, I started getting Not Found: /auth/user_profile ... which traced back to the second to last line in fpan/urls.py
`url(r'^auth/', RedirectView.as_view(pattern_name='fpan_home', permanent=True)),`
I added 
`    url(r'^auth/user_profile$', UserProfileView.as_view(), name='user_profile'),
`
above it since django matches urls in order.
It then threw another not found error on get_client_id, so I added that as well.

- once the above was done, I could connect with the app and create a new resource (I used the Scout Report as the basis for the project). I created a new scout report but upon syncing the data, the server through the following datetime format error when committing to postgres:
` TileValidationError: u"2020-03-11T00:00:00.000-04:00 None is not in the correct format, make sure it is in this format: ... or set the date format in settings.DATE_IMPORT_EXPORT_FORMAT.`

This error is generated by datatypes.py and tells you how to fix it...so, I've added the following to settings_local.py:
![image](https://user-images.githubusercontent.com/3217017/77589387-f0727d80-6ec1-11ea-8cd3-c0be8032f7f3.png)
but haven't hit upon the correct format yet. I'm a bit concerned by the "None" at the end. But I think that is related to the row_number and not the value the app is passing: 

` "message": f"{value} {row_number} is not in the correct format, make sure it is in this format: \
                            {date_format} or set the date format in settings.DATE_IMPORT_EXPORT_FORMAT. This data was not imported.",`

I haven't tried turning on TZ because I was afraid it would mess with the database, but that's another avenue I can explore along with looking at the graph model and card -- assuming it is the scout visit date in the scout report.

**Comment by coherit** [comment]
@mradamcox is fpan5 staging serving over ssl? It seems to resolve to http by default and I can't get to https:// (needed to test collector access)

![image](https://user-images.githubusercontent.com/3217017/78068705-db389b80-7366-11ea-803d-e43b228ead89.png)

**Comment by mradamcox** [comment]
@coherit Oh yeah, I disabled it for debugging other things. I'll enable SSL now.

**Comment by coherit** [comment]
On Arches 5 and getting a new error on this branch:
`RuntimeError: Model class models.region.Region doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.`

I've tried adding models.region to INSTALLED_APPS in settings_local, but no dice. Let me know if you've encountered this before.

**Comment by coherit** [comment]
ok...seems to be related to: https://medium.com/@michal.bock/fix-weird-exceptions-when-running-django-tests-f58def71b59a 

will be applying some of these suggested fixes.

**Comment by coherit** [comment]
Have caught back up to where I was in Arches 4 -- now on branch 85_up5_collector 
edits required in:

- urls.py
- auth.py
- apache conf for fpan5-ssl (needed to add WSGIPassAuthorization on)

Throwing the date error, so on to that next...

**Comment by mradamcox** [comment]
Looks like the Arches team picked up on your forum post: https://github.com/archesproject/arches/issues/6043

**Comment by coherit** [comment]
connection is working; will be addressing the date parsing issue separately.
