### ISSUE TITLE
Updating Land Management unit polygons on Arches map

### ISSUE THREAD

**Issue by kkemp85** [legiongis/hmsf-md#91]
Our contact at FWC informed us that some of the land units he manages don't have polygons that show up on the Arches map (the green polygons indicating public lands). He provided us with the example of Big Bend WMA - the northern Hickory Mound Unit is visible as well as the southern Tide Swamp unit, but the Spring Creek unit in the middle is missing in Arches (see images from google maps and arches). Patty and I noticed this issue with other FWC lands earlier and also for other land units. This will become an issue once we get to the step of making FWC accounts only see sites within their own land management units since we can't do this if the unit polygon doesn't exist in Arches. @mradamcox do you need me to create some shapefiles for you to get this corrected? Just let me know what you need from me!
![image](https://user-images.githubusercontent.com/54329725/71845921-5d326480-3097-11ea-83d7-36742e61e191.png)

![image](https://user-images.githubusercontent.com/54329725/71845985-8226d780-3097-11ea-908a-c3ccd415be1a.png)

**Comment by mradamcox** [comment]
@kkemp85 Interesting, a couple of things about this. First, the lack of the polygon on the basemap doesn't necessarily mean it's missing from Arches. The basemap we use is based on [Open Street Map](https://www.openstreetmap.org), so, in fact, it's absolutely possible to add the missing polygons to it, but it's an entirely different process. Here's a good place to start: https://wiki.openstreetmap.org/wiki/Beginners%27_guide.

As for Arches, I have these management areas loaded in behind the scenes, though it's a little off-kilter now because the original reason I loaded them in is not in use anymore. Right now, if a site needs to be added to that area, it would happen in the dropdown menus just like if it were assigned to a different Land Manager category.

To see the loaded in managed area objects (again, not _really_ in use at the moment), you can log into the /admin site and then find the ManagedArea objects there.

Hope that answers some of the questions here, and let me know what you think.

**Comment by kkemp85** [comment]
@mradamcox I actually took a class with Open Street Map so I already have a background in it, it's just been a while, but I remember it being really easy to navigate back then. If I do so, does that mean I can update our open street map to include those missing polygons myself?

**Comment by kkemp85** [comment]
@mradamcox Also, I see another issue here that I will have to discuss with FWC. The example I gave you above is about Big Bend WMA. It's a large WMA so the land parcels are separated into separate units and may have separate managers which will require separate accounts, and we don't have it set up that way now. I can easily set up new accounts if these units of the BigBendWMA need to be separated like that, but that will also require me to create new sections in the ManagedArea objects since these separate units aren't currently represented there (they are all one under Big Bend as of now). Something for me to think about after I contact FWC.

**Comment by kkemp85** [comment]
I am working on this myself so will close out this ticket
